- name: Filebeat on Webserver
  hosts: webservers
  become: true
  tasks:

		  - name: Download filebeat .deb file
			command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb

          - name: INstall filebeat .deb
            command: dpkg -i filebeat-7.6.1-amd64.deb

          - name: copy config file
            copy:
                    src: /etc/ansible/filebeat-config.yml
                    dest: /etc/filebeat/filebeat.yml

          - name: setup filebeat
            command: filebeat modules enable system

          - name: setup filebeat
            command: filebeat setup

          - name:  filebeat start
            command: service filebeat start

          - name: Enable service filebeat on boot
            systemd:
              name: filebeat
              enabled: yes

