- name: Metricbeat on Webserver
  hosts: webservers
  become: true
  tasks:
		  - name: Download metricbeat
			command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb


          - name: INstall metricbeat .deb
            command: dpkg -i metricbeat-7.4.0-amd64.deb

          - name: copy config file
            copy:
                    src: /etc/ansible/metricbeat.yml
                    dest: /etc/metricbeat/metricbeat.yml

          - name: setup  metricbeat
            command:  metricbeat modules enable docker

          - name: setup  metricbeat
            command:  metricbeat setup

          - name:   metricbeat start
            command: service  metricbeat start
			
		  - name: Enable service metricbeat on boot
			systemd:
			  name: metricbeat
			  enabled: yes

			
